[project]
name = "qlogicae-logis"
version = "3.1.0"
description = "The project orchestration tool for QLogicae projects"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Vaughn Cedric L. Araneta", email = "vaughncedriclipardoaraneta@gmail.com" }
]
maintainers = [
    { name = "Vaughn Cedric L. Araneta", email = "vaughncedriclipardoaraneta@gmail.com" }
]
keywords = ["qlogicae", "logis"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
    "Topic :: Software Development",
    "Topic :: Software Development :: Build Tools",
    "Topic :: System :: Installation/Setup",
    "Topic :: System :: Software Distribution",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
]
dependencies = []


[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
    "ruff",
    "mypy",
    "hatch",
    "twine",
    "memray",
    "scalene",
    "pympler",
    "vulture",
]

[project.scripts]
qlogicae-logis = "qlogicae_logis.v3.console.app:main"


[project.urls]
Homepage = "https://github.com/CedricDeVon/qlogicae-logis"
Repository = "https://github.com/CedricDeVon/qlogicae-logis"
Documentation = "https://github.com/CedricDeVon/qlogicae-logis"
Issues = "https://github.com/CedricDeVon/qlogicae-logis/issues"
Changelog = "https://github.com/CedricDeVon/qlogicae-logis/releases"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pytest.ini_options]
pythonpath = ["."]
python_files = ["test_*.py"]
addopts = "-ra"
# testpaths = ["./test/qlogicae_logis/v3/unit"]


[tool.coverage.run]
source = []
branch = true


[tool.hatch.build]
include = [
    "qlogicae_logis/**/*",
    "qlogicae_logis/py.typed",
]
exclude = [
    "**/__pycache__",
    "**/*.pyc",
    "test",
    ".github",
    ".gitignore",
    ".vscode",
    "requirements.txt",
    "output",
    "docs/**",
    "project/**",
]

[tool.coverage.report]
show_missing = true
skip_covered = false

[tool.ruff]
target-version = "py314"
line-length = 88
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".output",
    "output",
    ".outputs",
    "outputs",
    ".dist",
    "dist",
    ".build",
    "build",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    ".tox",
    ".nox",
    ".idea",
    ".vscode",
    "qlogicae_logis/v3/_vendor",
]

[tool.ruff.lint]
select = [    
    "E",
    "W", # pycodestyle    
    "F", # Pyflakes    
    "I", # isort    
    "UP", # pyupgrade    
    "B", # flake8-bugbear
    "PTH", # pathlib
]
ignore = [        
    "E731",
    "B008",
    "S607",    
    "S101", # allow assert statements    
    "S603", # allow subprocess usage
    "PLR2004", # allow magic values
]
fixable = ["ALL"]
unfixable = []


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
skip-magic-trailing-comma = false

[tool.mypy]
files = [
    "qlogicae_logis/v3",
]
exclude = [
    '(^|/)_vendor(/|$)',
]
strict = true
python_version = "3.12"
namespace_packages = true
explicit_package_bases = true
show_error_codes = true
pretty = true
color_output = true
show_column_numbers = true
show_error_context = true

[[tool.mypy.overrides]]
module = [
    "qlogicae_logis.v3._vendor.*",
]
ignore_errors = true


[tool.vulture]
exclude = [
    "qlogicae_logis/v3/_vendor/qlogicae_cor/v2/library/log_format.py",
    "qlogicae_logis/v3/_vendor/qlogicae_cor/v2/library/timestamp_manager.py",
]



[tool.hatch.build.targets.wheel]
packages = ["qlogicae_logis"]


[tool.hatch.build.targets.wheel.force-include]
"qlogicae_logis/py.typed" = "qlogicae_logis/py.typed"

[tool.hatch.envs.default.scripts]
test-import-references = """
    vulture qlogicae_logis
"""

minify = """
    pyminify \
        --in-place \
        --prefer-single-line \
        --remove-debug \
        --remove-asserts \
        --remove-literal-statements \
        --remove-class-attribute-annotations \
        qlogicae_logis/v3
"""
test-lint = """
    ruff check qlogicae_logis/v3/console qlogicae_logis/v3/library --fix
"""
test-type-check = """
    mypy 
"""
test-unit = """
    pytest -vv \
        --cov \
        --cov-branch \
        --cov-report=term-missing \
        --cov-report=html:\"output/test/unit/html\" \
        --cov-report=xml:\"output/test/unit/coverage.xml\" \
        --cov-report=json:\"output/test/unit/coverage.json\" \
        --junitxml=\"output/test/unit/junit.xml\" \
"""
test-benchmark-memory-usage-create = """
    memray run -o output/test/benchmark/memray-1.bin -m test.qlogicae_logis.v3.benchmark.memory_usage.test_usage ;
"""
# memray run -o output/test/benchmark/memray-2.bin -m test.qlogicae_logis.v3.benchmark.memory_usage.test_dynamic
test-benchmark-memory-usage-view = """
    memray tree output/test/benchmark/memray-1.bin
"""
# memray tree output/test/benchmark/memray-2.bin
test-pip-deployment = """
    twine check --strict output/build/release/dist/*
"""
deploy = """
    twine upload output/build/release/dist/* --config-file .pypirc
"""

github-workflow-setup = """
    mkdir -p output/build/release &&
    mkdir -p output/test/unit &&
    mkdir -p output/test/benchmark
"""
github-workflow-test-import-references = """
    hatch run github-workflow-setup &&
    hatch run test-import-references
"""
github-workflow-test-type-check = """
    hatch run github-workflow-setup &&
    hatch run test-type-check
"""
github-workflow-test-lint = """
    hatch run github-workflow-setup &&
    hatch run test-lint
"""
github-workflow-test-unit = """
    hatch run github-workflow-setup &&
    hatch run test-unit
"""
github-workflow-test-benchmark-memory-usage-create = """
    hatch run github-workflow-setup &&
    hatch run test-benchmark-memory-usage-create
"""
github-workflow-test-benchmark-memory-usage-view = """
    hatch run github-workflow-setup &&
    hatch run test-benchmark-memory-usage-view
"""

# scalene run --html --outfile output/test/benchmark/scalene.html test/qlogicae_logis/v3/benchmark/memory_usage/test_static.py
# memray run -o output/test/benchmark/memray.bin -m test.qlogicae_logis.v3.benchmark.memory_usage.test_static
# scalene view output/test/benchmark/scalene.json
# memray tree output/test/benchmark/memray.bin
#     scalene view output/test/benchmark/scalene.json